baseurl = "https://blog.copypastedeveloper.com"
languageCode = "en"
title = "Copy Paste Developer"
theme = "hucore"
copyright = "&copy; 2017"
disqusShortname = "shortname"
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["C#","Development","Process"]
author = "Nathan Gonzalez"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "js","c#"]

[[params.social]]
url = "https://github.com/copypastedeveloper"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/shortmandevelopment"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/nathancgonzalez"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"